from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^login.html$', views.user_login, name='user_login'),
    url(r'^confirm.html$', views.confirm, name='confirm'),

    url(r'^housemaster/$', views.housemaster__index, name='housemaster__index'),
    url(r'^housemaster/add_visitor.html$', views.housemaster__add_visitor, name='housemaster__add_visitor'),
    url(r'^housemaster/new_visitor.html$', views.housemaster__new_visitor, name='housemaster__new_visitor'),
    url(r'^housemaster/building.html$', views.housemaster__building, name='housemaster__building'),
    url(r'^housemaster/checkin.html$', views.housemaster__checkin, name='housemaster__checkin'),
    url(r'^housemaster/checkin_result.html$', views.housemaster__checkin_result, name='housemaster__checkin_result'),
    url(r'^housemaster/index.html$', views.housemaster__index, name='housemaster__index'),
    url(r'^housemaster/lookup.html$', views.housemaster__lookup, name='housemaster__lookup'),
    url(r'^housemaster/lookup_result.html$', views.housemaster__lookup_result, name='housemaster__lookup_result'),
    url(r'^housemaster/(?P<roomid>.*)/member.html$', views.housemaster__member, name='housemaster__member'),
    url(r'^housemaster/unsubscribe.html$', views.housemaster__unsubscribe, name='housemaster__unsubscribe'),
    url(r'^housemaster/unsubscribe_result.html$', views.housemaster__unsubscribe_result, name='housemaster__unsubscribe_result'),
    url(r'^housemaster/visitor.html$', views.housemaster__visitor, name='housemaster__visitor'),
    url(r'^housemaster/mark.html$', views.housemaster__mark, name='housemaster__mark'),
    url(r'^housemaster/new_mark.html$', views.housemaster__new_mark, name='housemaster__new_mark'),

    url(r'^instructor/$', views.instructor__index, name='instructor__index'),
    url(r'^instructor/checkin.html$', views.instructor__checkin, name='instructor__checkin'),
    url(r'^instructor/checkin_result.html$', views.instructor__checkin_result, name='instructor__checkin_result'),
    url(r'^instructor/(?P<classid>.*)/class.html$', views.instructor__class, name='instructor__class'),
    url(r'^instructor/index.html$', views.instructor__index, name='instructor__index'),
    url(r'^instructor/lookup.html$', views.instructor__lookup, name='instructor__lookup'),
    url(r'^instructor/lookup_result.html$', views.instructor__lookup_result, name='instructor__lookup_result'),
    url(r'^instructor/(?P<sno>.*)/member.html$', views.instructor__member, name='instructor__member'),
    url(r'^instructor/unsubscribe.html$', views.instructor__unsubscribe, name='instructor__unsubscribe'),
    url(r'^instructor/unsubscribe_result.html$', views.instructor__unsubscribe_result, name='instructor__unsubscribe_result'),

    url(r'^maintenance/$', views.maintenance__index, name='maintenance__index'),
    url(r'^maintenance/index.html$', views.maintenance__index, name='maintenance__index'),
    url(r'^maintenance/(?P<repairid>.*)/repair.html$', views.maintenance__repair, name='maintenance__repair'),
    url(r'^maintenance/(?P<repairid>.*)/repair_result.html$', views.maintenance__repair_result, name='maintenance__repair_result'),

    url(r'^secretary/$', views.secretary__index, name='secretary__index'),
    url(r'^secretary/building.html$', views.secretary__building, name='secretary__building'),
    url(r'^secretary/checkin.html$', views.secretary__checkin, name='secretary__checkin'),
    url(r'^secretary/checkin_result.html$', views.secretary__checkin_result, name='secretary__checkin_result'),
    url(r'^secretary/(?P<classid>.*)/class.html$', views.secretary__class, name='secretary__class'),
    url(r'^secretary/index.html$', views.secretary__index, name='secretary__index'),
    url(r'^secretary/lookup.html$', views.secretary__lookup, name='secretary__lookup'),
    url(r'^secretary/lookup_result.html$', views.secretary__lookup_result, name='secretary__lookup_result'),
    url(r'^secretary/(?P<sno>.*)/member.html$', views.secretary__member, name='secretary__member'),
    url(r'^secretary/unsubscribe.html$', views.secretary__unsubscribe, name='secretary__unsubscribe'),
    url(r'^secretary/unsubscribe_result.html$', views.secretary__unsubscribe_result, name='secretary__unsubscribe_result'),

    url(r'^student/$', views.student__index, name='student__index'),
    url(r'^student/(?P<roomid>.*)/checkin.html$', views.student__checkin, name='student__checkin'),
    url(r'^student/(?P<buildingid>.*)/building.html$', views.student__building, name='student__building'),
    url(r'^student/building_select.html$', views.student__building_select, name='student__building_select'),
    url(r'^student/fee.html$', views.student__fee, name='student__fee'),
    url(r'^student/index.html$', views.student__index, name='student__index'),
    url(r'^student/mark.html$', views.student__mark, name='student__mark'),
    url(r'^student/repair.html$', views.student__repair, name='student__repair'),
    url(r'^student/new_repair.html$', views.student__new_repair, name='student__new_repair'),
    url(r'^student/repair_record.html$', views.student__repair_record, name='student__repair_record'),
    url(r'^student/unsubscribe.html$', views.student__unsubscribe, name='student__unsubscribe'),
    url(r'^student/unsubscribe_result.html$', views.student__unsubscribe_result, name='student__unsubscribe_result'),
]
