# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 01:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('amount', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EnterApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('housemaster_check', models.NullBooleanField()),
                ('instructor_check', models.NullBooleanField()),
                ('secretary_check', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Housemaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=200, null=True)),
                ('buildingid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dorm.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_time', models.DateTimeField()),
                ('quit_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('score', models.FloatField()),
                ('remark', models.TextField(null=True)),
                ('housemasterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.Housemaster')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuitApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('reason', models.TextField()),
                ('housemaster_check', models.NullBooleanField()),
                ('instructor_check', models.NullBooleanField()),
                ('secretary_check', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
                ('book_dt', models.DateTimeField()),
                ('reason', models.TextField(null=True)),
                ('fix_dt', models.DateTimeField(null=True)),
                ('remark', models.TextField(null=True)),
                ('maintenanceid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dorm.Maintenance')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('room_type', models.CharField(max_length=20, null=True)),
                ('capacity', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=200, null=True)),
                ('collegeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.College')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.NullBooleanField()),
                ('contact', models.CharField(max_length=200, null=True)),
                ('classid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dorm.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.BooleanField()),
                ('document_type', models.CharField(max_length=20, null=True)),
                ('documentno', models.CharField(max_length=20, null=True)),
                ('contact', models.CharField(max_length=200, null=True)),
                ('dt', models.DateTimeField()),
                ('housemasterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.Housemaster')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('roomid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dorm.Room')),
                ('remain', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='roomid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dorm.Room'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.Owner'),
        ),
        migrations.AddField(
            model_name='room',
            name='buildingid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.Building'),
        ),
        migrations.AddField(
            model_name='repair',
            name='roomid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.Room'),
        ),
        migrations.AddField(
            model_name='quitapply',
            name='roomid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.Room'),
        ),
        migrations.AddField(
            model_name='quitapply',
            name='sno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.Student'),
        ),
        migrations.AddField(
            model_name='mark',
            name='roomid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.Room'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.Owner'),
        ),
        migrations.AddField(
            model_name='liverecord',
            name='roomid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.Room'),
        ),
        migrations.AddField(
            model_name='liverecord',
            name='sno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.Student'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.Owner'),
        ),
        migrations.AddField(
            model_name='housemaster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.Owner'),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='roomid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.Room'),
        ),
        migrations.AddField(
            model_name='enterapply',
            name='roomid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.Room'),
        ),
        migrations.AddField(
            model_name='enterapply',
            name='sno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorm.Student'),
        ),
        migrations.AddField(
            model_name='class',
            name='collegeid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dorm.College'),
        ),
        migrations.AddField(
            model_name='class',
            name='instructorid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dorm.Instructor'),
        ),
        migrations.AlterUniqueTogether(
            name='repair',
            unique_together=set([('item', 'roomid', 'book_dt')]),
        ),
        migrations.AlterUniqueTogether(
            name='quitapply',
            unique_together=set([('sno', 'roomid', 'dt')]),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together=set([('roomid', 'dt')]),
        ),
        migrations.AlterUniqueTogether(
            name='liverecord',
            unique_together=set([('sno', 'roomid', 'enter_time')]),
        ),
        migrations.AlterUniqueTogether(
            name='feerecord',
            unique_together=set([('roomid', 'dt')]),
        ),
        migrations.AlterUniqueTogether(
            name='enterapply',
            unique_together=set([('sno', 'roomid', 'dt')]),
        ),
    ]
